name: Devops CI Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: list all files 
        run: ls -R 
      - name : show pwd 
        run: pwd
      - name : install packages
        run : pip install -r .github/workflows/requirements.txt
      - name: Build step 
        run: echo "Build completed"
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
       - name: checkout
         uses: actions/checkout@v3
       - name: Run test
         run: echo "running tests"
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy step
        run: echo "Deploying application"
      - name: run python file
        run: python .github/workflows/app.py
      - name: Run tests
        run: pytest


        

