name: CI 

on: push

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name:
        run: ls -a
      - name : Run python file
        run: python .github/workflows/app.py
        
